// Code generated by ent, DO NOT EDIT.

package ent

import (
	"booking-flight-system/ent/airport"
	"booking-flight-system/ent/booking"
	"booking-flight-system/ent/customer"
	"booking-flight-system/ent/flight"
	"booking-flight-system/ent/plane"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FlightCreate is the builder for creating a Flight entity.
type FlightCreate struct {
	config
	mutation *FlightMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (fc *FlightCreate) SetCreatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetCreatedAt(t)
	return fc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableCreatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetCreatedAt(*t)
	}
	return fc
}

// SetUpdatedAt sets the "updated_at" field.
func (fc *FlightCreate) SetUpdatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetUpdatedAt(t)
	return fc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableUpdatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetUpdatedAt(*t)
	}
	return fc
}

// SetName sets the "name" field.
func (fc *FlightCreate) SetName(s string) *FlightCreate {
	fc.mutation.SetName(s)
	return fc
}

// SetDepartAt sets the "depart_at" field.
func (fc *FlightCreate) SetDepartAt(t time.Time) *FlightCreate {
	fc.mutation.SetDepartAt(t)
	return fc
}

// SetLandAt sets the "land_at" field.
func (fc *FlightCreate) SetLandAt(t time.Time) *FlightCreate {
	fc.mutation.SetLandAt(t)
	return fc
}

// SetAvailableEcSlot sets the "available_ec_slot" field.
func (fc *FlightCreate) SetAvailableEcSlot(i int) *FlightCreate {
	fc.mutation.SetAvailableEcSlot(i)
	return fc
}

// SetAvailableBcSlot sets the "available_bc_slot" field.
func (fc *FlightCreate) SetAvailableBcSlot(i int) *FlightCreate {
	fc.mutation.SetAvailableBcSlot(i)
	return fc
}

// SetStatus sets the "status" field.
func (fc *FlightCreate) SetStatus(f flight.Status) *FlightCreate {
	fc.mutation.SetStatus(f)
	return fc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fc *FlightCreate) SetNillableStatus(f *flight.Status) *FlightCreate {
	if f != nil {
		fc.SetStatus(*f)
	}
	return fc
}

// SetPlaneID sets the "plane_id" field.
func (fc *FlightCreate) SetPlaneID(i int) *FlightCreate {
	fc.mutation.SetPlaneID(i)
	return fc
}

// SetNillablePlaneID sets the "plane_id" field if the given value is not nil.
func (fc *FlightCreate) SetNillablePlaneID(i *int) *FlightCreate {
	if i != nil {
		fc.SetPlaneID(*i)
	}
	return fc
}

// SetAirportID sets the "airport_id" field.
func (fc *FlightCreate) SetAirportID(i int) *FlightCreate {
	fc.mutation.SetAirportID(i)
	return fc
}

// SetNillableAirportID sets the "airport_id" field if the given value is not nil.
func (fc *FlightCreate) SetNillableAirportID(i *int) *FlightCreate {
	if i != nil {
		fc.SetAirportID(*i)
	}
	return fc
}

// SetCustomerID sets the "customer_id" field.
func (fc *FlightCreate) SetCustomerID(i int) *FlightCreate {
	fc.mutation.SetCustomerID(i)
	return fc
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (fc *FlightCreate) SetNillableCustomerID(i *int) *FlightCreate {
	if i != nil {
		fc.SetCustomerID(*i)
	}
	return fc
}

// SetHasPlaneID sets the "has_plane" edge to the Plane entity by ID.
func (fc *FlightCreate) SetHasPlaneID(id int) *FlightCreate {
	fc.mutation.SetHasPlaneID(id)
	return fc
}

// SetNillableHasPlaneID sets the "has_plane" edge to the Plane entity by ID if the given value is not nil.
func (fc *FlightCreate) SetNillableHasPlaneID(id *int) *FlightCreate {
	if id != nil {
		fc = fc.SetHasPlaneID(*id)
	}
	return fc
}

// SetHasPlane sets the "has_plane" edge to the Plane entity.
func (fc *FlightCreate) SetHasPlane(p *Plane) *FlightCreate {
	return fc.SetHasPlaneID(p.ID)
}

// AddHasBookingIDs adds the "has_booking" edge to the Booking entity by IDs.
func (fc *FlightCreate) AddHasBookingIDs(ids ...int) *FlightCreate {
	fc.mutation.AddHasBookingIDs(ids...)
	return fc
}

// AddHasBooking adds the "has_booking" edges to the Booking entity.
func (fc *FlightCreate) AddHasBooking(b ...*Booking) *FlightCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return fc.AddHasBookingIDs(ids...)
}

// SetHasAirportID sets the "has_Airport" edge to the Airport entity by ID.
func (fc *FlightCreate) SetHasAirportID(id int) *FlightCreate {
	fc.mutation.SetHasAirportID(id)
	return fc
}

// SetNillableHasAirportID sets the "has_Airport" edge to the Airport entity by ID if the given value is not nil.
func (fc *FlightCreate) SetNillableHasAirportID(id *int) *FlightCreate {
	if id != nil {
		fc = fc.SetHasAirportID(*id)
	}
	return fc
}

// SetHasAirport sets the "has_Airport" edge to the Airport entity.
func (fc *FlightCreate) SetHasAirport(a *Airport) *FlightCreate {
	return fc.SetHasAirportID(a.ID)
}

// SetHasCustomerID sets the "has_Customer" edge to the Customer entity by ID.
func (fc *FlightCreate) SetHasCustomerID(id int) *FlightCreate {
	fc.mutation.SetHasCustomerID(id)
	return fc
}

// SetNillableHasCustomerID sets the "has_Customer" edge to the Customer entity by ID if the given value is not nil.
func (fc *FlightCreate) SetNillableHasCustomerID(id *int) *FlightCreate {
	if id != nil {
		fc = fc.SetHasCustomerID(*id)
	}
	return fc
}

// SetHasCustomer sets the "has_Customer" edge to the Customer entity.
func (fc *FlightCreate) SetHasCustomer(c *Customer) *FlightCreate {
	return fc.SetHasCustomerID(c.ID)
}

// Mutation returns the FlightMutation object of the builder.
func (fc *FlightCreate) Mutation() *FlightMutation {
	return fc.mutation
}

// Save creates the Flight in the database.
func (fc *FlightCreate) Save(ctx context.Context) (*Flight, error) {
	fc.defaults()
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FlightCreate) SaveX(ctx context.Context) *Flight {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FlightCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FlightCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FlightCreate) defaults() {
	if _, ok := fc.mutation.CreatedAt(); !ok {
		v := flight.DefaultCreatedAt()
		fc.mutation.SetCreatedAt(v)
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		v := flight.DefaultUpdatedAt()
		fc.mutation.SetUpdatedAt(v)
	}
	if _, ok := fc.mutation.Status(); !ok {
		v := flight.DefaultStatus
		fc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FlightCreate) check() error {
	if _, ok := fc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Flight.created_at"`)}
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Flight.updated_at"`)}
	}
	if _, ok := fc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Flight.name"`)}
	}
	if v, ok := fc.mutation.Name(); ok {
		if err := flight.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Flight.name": %w`, err)}
		}
	}
	if _, ok := fc.mutation.DepartAt(); !ok {
		return &ValidationError{Name: "depart_at", err: errors.New(`ent: missing required field "Flight.depart_at"`)}
	}
	if _, ok := fc.mutation.LandAt(); !ok {
		return &ValidationError{Name: "land_at", err: errors.New(`ent: missing required field "Flight.land_at"`)}
	}
	if _, ok := fc.mutation.AvailableEcSlot(); !ok {
		return &ValidationError{Name: "available_ec_slot", err: errors.New(`ent: missing required field "Flight.available_ec_slot"`)}
	}
	if _, ok := fc.mutation.AvailableBcSlot(); !ok {
		return &ValidationError{Name: "available_bc_slot", err: errors.New(`ent: missing required field "Flight.available_bc_slot"`)}
	}
	if _, ok := fc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Flight.status"`)}
	}
	if v, ok := fc.mutation.Status(); ok {
		if err := flight.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Flight.status": %w`, err)}
		}
	}
	return nil
}

func (fc *FlightCreate) sqlSave(ctx context.Context) (*Flight, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FlightCreate) createSpec() (*Flight, *sqlgraph.CreateSpec) {
	var (
		_node = &Flight{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(flight.Table, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt))
	)
	if value, ok := fc.mutation.CreatedAt(); ok {
		_spec.SetField(flight.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fc.mutation.UpdatedAt(); ok {
		_spec.SetField(flight.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := fc.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := fc.mutation.DepartAt(); ok {
		_spec.SetField(flight.FieldDepartAt, field.TypeTime, value)
		_node.DepartAt = value
	}
	if value, ok := fc.mutation.LandAt(); ok {
		_spec.SetField(flight.FieldLandAt, field.TypeTime, value)
		_node.LandAt = value
	}
	if value, ok := fc.mutation.AvailableEcSlot(); ok {
		_spec.SetField(flight.FieldAvailableEcSlot, field.TypeInt, value)
		_node.AvailableEcSlot = value
	}
	if value, ok := fc.mutation.AvailableBcSlot(); ok {
		_spec.SetField(flight.FieldAvailableBcSlot, field.TypeInt, value)
		_node.AvailableBcSlot = value
	}
	if value, ok := fc.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := fc.mutation.HasPlaneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.HasPlaneTable,
			Columns: []string{flight.HasPlaneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plane.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlaneID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.HasBookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.HasBookingTable,
			Columns: []string{flight.HasBookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.HasAirportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.HasAirportTable,
			Columns: []string{flight.HasAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AirportID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.HasCustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.HasCustomerTable,
			Columns: []string{flight.HasCustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FlightCreateBulk is the builder for creating many Flight entities in bulk.
type FlightCreateBulk struct {
	config
	builders []*FlightCreate
}

// Save creates the Flight entities in the database.
func (fcb *FlightCreateBulk) Save(ctx context.Context) ([]*Flight, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Flight, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FlightCreateBulk) SaveX(ctx context.Context) []*Flight {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FlightCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FlightCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
