version: "3.7"

networks:
  booking:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: booking_flight_system
      POSTGRES_USER: hachan
      POSTGRES_PASSWORD: hachan
      TZ: "GMT+7"
      PGTZ: "GMT+7"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"
    networks:
      - booking

  # backend-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["api"]
  #   depends_on:
  #     - db
  #   restart: always
  #   environment:
  #     POSTGRES_CONNECTION_STRING: "postgres://backend_user:backend_password@db:5432/backend_db?sslmode=disable"
  #   links:
  #     - db
  #   ports:
  #     - '8000:8000'
  #   networks:
  #     - golang-boilerplate