create table airports
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    name       varchar                  not null,
    lat        double precision         not null,
    long       double precision         not null
);

alter table airports
    owner to hachan;

create unique index airports_name_key
    on airports (name);

