create table flights
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp with time zone                    not null,
    updated_at        timestamp with time zone                    not null,
    name              varchar                                     not null,
    depart_at         timestamp with time zone                    not null,
    land_at           timestamp with time zone                    not null,
    available_ec_slot bigint                                      not null,
    available_bc_slot bigint                                      not null,
    status            varchar default 'LANDED'::character varying not null,
    from_airport_id   bigint
        constraint flights_airports_from_flight
            references airports
            on delete set null,
    to_airport_id     bigint
        constraint flights_airports_to_flight
            references airports
            on delete set null,
    plane_id          bigint
        constraint flights_planes_flights
            references planes
            on delete set null
);

alter table flights
    owner to hachan;

