create table planes
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp with time zone                  not null,
    updated_at           timestamp with time zone                  not null,
    name                 varchar                                   not null,
    economy_class_slots  bigint  default 0                         not null,
    business_class_slots bigint  default 0                         not null,
    status               varchar default 'FREE'::character varying not null
);

alter table planes
    owner to hachan;

