package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"booking-flight-system/ent"
	graphql1 "booking-flight-system/graphql"
	"context"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input *ent.CreateMemberInput) (*ent.Member, error) {
	return r.client.Member.Create().SetEmail(input.Email).
		SetPassword(input.Password).
		SetFullName(input.FullName).
		SetDob(input.Dob).
		SetCid(input.Cid).Save(ctx)
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
