package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"booking-flight-system/ent"
	graphql1 "booking-flight-system/graphql"
	"context"
	"fmt"
)

// Node is the resolver for the node field.
func (r *planeEdgeResolver) Node(ctx context.Context, obj *ent.PlaneEdge) (*ent.Member, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// PlaneEdge returns graphql1.PlaneEdgeResolver implementation.
func (r *Resolver) PlaneEdge() graphql1.PlaneEdgeResolver { return &planeEdgeResolver{r} }

type planeEdgeResolver struct{ *Resolver }
