// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

import (
	"booking-flight-system/ent/booking"
	"booking-flight-system/ent/flight"
	"time"
)

type CreateFlight struct {
	Name     string    `json:"name"`
	DepartAt time.Time `json:"departAt"`
	LandAt   time.Time `json:"landAt"`
	ToID     int       `json:"toID"`
	FromID   int       `json:"fromID"`
	PlaneID  int       `json:"planeID"`
}

type CustomerBooking struct {
	SeatType   booking.SeatType `json:"seatType"`
	FlightID   int              `json:"flight_id"`
	CustomerID int              `json:"customer_id"`
	Status     *booking.Status  `json:"status,omitempty"`
}

type CustomerInput struct {
	Email       string     `json:"email"`
	PhoneNumber string     `json:"phoneNumber"`
	FullName    string     `json:"fullName"`
	Dob         *time.Time `json:"dob,omitempty"`
	Cid         string     `json:"cid"`
}

type MemberBooking struct {
	SeatType booking.SeatType `json:"seatType"`
	FlightID int              `json:"flight_id"`
	Status   *booking.Status  `json:"status,omitempty"`
}

type SearchBooking struct {
	FlightID    int    `json:"flight_id"`
	BookingCode string `json:"booking_code"`
	Cid         string `json:"cid"`
}

type SearchFlight struct {
	FromAirport string    `json:"from_airport"`
	ToAirport   string    `json:"to_airport"`
	DepartAt    time.Time `json:"depart_at"`
}

type Token struct {
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expired_at"`
}

type UpdateFlightSlot struct {
	AvailableEcSlots int `json:"available_ec_slots"`
	AvailableBcSlots int `json:"available_bc_slots"`
}

type UpdateFlightStatus struct {
	Status flight.Status `json:"status"`
}
