// Code generated by ent, DO NOT EDIT.

package ent

import (
	"booking-flight-sytem/ent/flight"
	"booking-flight-sytem/ent/plane"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlaneCreate is the builder for creating a Plane entity.
type PlaneCreate struct {
	config
	mutation *PlaneMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PlaneCreate) SetName(s string) *PlaneCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetEconomyClassSlots sets the "economy_class_slots" field.
func (pc *PlaneCreate) SetEconomyClassSlots(i int64) *PlaneCreate {
	pc.mutation.SetEconomyClassSlots(i)
	return pc
}

// SetBusinessClassSlots sets the "business_class_slots" field.
func (pc *PlaneCreate) SetBusinessClassSlots(i int64) *PlaneCreate {
	pc.mutation.SetBusinessClassSlots(i)
	return pc
}

// SetStatus sets the "status" field.
func (pc *PlaneCreate) SetStatus(pl plane.Status) *PlaneCreate {
	pc.mutation.SetStatus(pl)
	return pc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pc *PlaneCreate) SetNillableStatus(pl *plane.Status) *PlaneCreate {
	if pl != nil {
		pc.SetStatus(*pl)
	}
	return pc
}

// AddFlightIDs adds the "flights" edge to the Flight entity by IDs.
func (pc *PlaneCreate) AddFlightIDs(ids ...int) *PlaneCreate {
	pc.mutation.AddFlightIDs(ids...)
	return pc
}

// AddFlights adds the "flights" edges to the Flight entity.
func (pc *PlaneCreate) AddFlights(f ...*Flight) *PlaneCreate {
	ids := make([]int, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return pc.AddFlightIDs(ids...)
}

// Mutation returns the PlaneMutation object of the builder.
func (pc *PlaneCreate) Mutation() *PlaneMutation {
	return pc.mutation
}

// Save creates the Plane in the database.
func (pc *PlaneCreate) Save(ctx context.Context) (*Plane, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PlaneCreate) SaveX(ctx context.Context) *Plane {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PlaneCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PlaneCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PlaneCreate) defaults() {
	if _, ok := pc.mutation.Status(); !ok {
		v := plane.DefaultStatus
		pc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PlaneCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plane.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := plane.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plane.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.EconomyClassSlots(); !ok {
		return &ValidationError{Name: "economy_class_slots", err: errors.New(`ent: missing required field "Plane.economy_class_slots"`)}
	}
	if _, ok := pc.mutation.BusinessClassSlots(); !ok {
		return &ValidationError{Name: "business_class_slots", err: errors.New(`ent: missing required field "Plane.business_class_slots"`)}
	}
	if _, ok := pc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Plane.status"`)}
	}
	if v, ok := pc.mutation.Status(); ok {
		if err := plane.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Plane.status": %w`, err)}
		}
	}
	return nil
}

func (pc *PlaneCreate) sqlSave(ctx context.Context) (*Plane, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PlaneCreate) createSpec() (*Plane, *sqlgraph.CreateSpec) {
	var (
		_node = &Plane{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(plane.Table, sqlgraph.NewFieldSpec(plane.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(plane.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.EconomyClassSlots(); ok {
		_spec.SetField(plane.FieldEconomyClassSlots, field.TypeInt64, value)
		_node.EconomyClassSlots = value
	}
	if value, ok := pc.mutation.BusinessClassSlots(); ok {
		_spec.SetField(plane.FieldBusinessClassSlots, field.TypeInt64, value)
		_node.BusinessClassSlots = value
	}
	if value, ok := pc.mutation.Status(); ok {
		_spec.SetField(plane.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := pc.mutation.FlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plane.FlightsTable,
			Columns: []string{plane.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlaneCreateBulk is the builder for creating many Plane entities in bulk.
type PlaneCreateBulk struct {
	config
	builders []*PlaneCreate
}

// Save creates the Plane entities in the database.
func (pcb *PlaneCreateBulk) Save(ctx context.Context) ([]*Plane, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Plane, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PlaneCreateBulk) SaveX(ctx context.Context) []*Plane {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PlaneCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PlaneCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
